### ISSUE TITLE
[BUG] Overlap 4+ Cols

### ISSUE THREAD

**Issue by reilldesign** [markmead/js-masonry#1]
This is a fantastic script in combination with grid styles. As long as i work with a maximum of three columns it works perfectly. With 4 columns there is sometimes overlapping of the items.

**Comment by markmead** [comment]
Interesting... It seems to happen when there is a `col-span-4` but with 6 grid items 🤔

**Comment by markmead** [comment]
Hey, @reilldesign can you give this URL a try? 

https://cdn.jsdelivr.net/gh/markmead/js-masonry@hotfix/awkward-cols/dist/masonry.min.js

**Comment by reilldesign** [comment]
Hi,

now i need a small { pollDuration: 250 } which was not necessary with three columns, but it works smoothly. Thanks a lot for this fantastic script.

**Comment by markmead** [comment]
Hmm, that's odd. I didn't need that in my testing... Glad it works tho, I'll get the PR merged.
